name: cancionero_liturgico
description: "Aplicación para gestión de canciones litúrgicas con acordes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8  
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2 # Asegúrate de usar la última versión compatible

  # También necesitas wakelock_plus para el modo presentación
  wakelock_plus: ^1.2.5
  device_info_plus: ^9.0.0
  http: ^1.1.0
  collection: ^1.18.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

