name: cancionero_liturgico
description: "Aplicación para gestión de canciones litúrgicas con acordes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  share_plus: ^7.0.0
  file_picker: ^5.0.0
  wakelock_plus: ^1.0.1
  scroll_to_index: ^2.0.0
  json_annotation: ^4.8.1
  uuid: ^4.2.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true